#!/bin/bash
#SBATCH -N 4
#SBATCH -n 224
#SBATCH -o myjob.%j.out
#SBATCH -J PeleCPlasma
#SBATCH -p development
#SBATCH -A CTS21022
#SBATCH -t 00:30:00

module load gcc

module list
pwd
date

#ibrun -n 32 ./PeleC3d.gnu.MPI.ex inputs.3d
mpirun -n 224 ./PeleC3d.gnu.MPI.ex inputs.3d
