#!/bin/bash
#SBATCH -N 4
#SBATCH -n 182
#SBATCH -o myjob.%j.out
#SBATCH -J PeleCPlasma
#SBATCH -p skx-dev
#SBATCH -A TG-CTS180002
#SBATCH -t 00:30:00

module load gcc

module list
pwd
date


mpirun -n 192 ./PeleC3d.gnu.MPI.ex inputs.3d
#mpirun -n 192 ./PeleC3d.gnu.MPI.ex inputs.3d amr.restart=chk00510
