#!/bin/bash
#SBATCH -N 16
#SBATCH -n 768
#SBATCH -o myjob.%j.out
#SBATCH -J PeleCPlasma
#SBATCH -p skx-normal
#SBATCH -A TG-CTS180002
#SBATCH -t 00:30:00

module load gcc

module list
pwd
date


#ibrun -n 32 ./PeleC3d.gnu.MPI.ex inputs.3d
mpirun -n 768 ./PeleC3d.gnu.TPROF.MPI.PLASMA.ex inputs.3d
