#include <iomanip>
#include <iostream>
#include <memory>
#include <string>
#include <ctime>

#ifdef AMREX_USE_OMP
#include <omp.h>
#endif

#include <AMReX_Utility.H>
#include <AMReX_buildInfo.H>
#include <AMReX_ParmParse.H>
#include <AMReX_PlotFileUtil.H>
#include <AMReX_VisMF.H>
#include <AMReX_EBMultiFabUtil.H>

#include "mechanism.H"
#include "PltFileManager.H"

#include "PeleC.H"
#include "IO.H"
#include "IndexDefines.H"

// PeleC maintains an internal checkpoint version numbering system.
// This allows us to maintain backwards compatibility with checkpoints
// generated by old versions of the code, so that new versions can
// restart from them. The version number is stored in the PeleCHeader
// file inside a checkpoint. The following were the changes that were made
// in updating version numbers:
// 0: all checkpoints as of 11/21/16
// 1: add body state

namespace {
int input_version = -1;
int current_version = 1;
std::string body_state_filename = "body_state.fab";
} // namespace

// I/O routines for PeleC

bool
PeleC::check_state_in_checkpoint(const StateType state_type)
{
  const std::string state_pfx =
    "Level_" + std::to_string(level) + "/SD_" + std::to_string(state_type);

  const std::string filename = parent->theRestartFile();
  const std::string faHeaderFilesName(filename + "/FabArrayHeaders.txt");
  amrex::Vector<char> faHeaderFileChars;
  bool bExitOnError(false); // ---- dont exit if this file does not exist
  amrex::ParallelDescriptor::ReadAndBcastFile(
    faHeaderFilesName, faHeaderFileChars, bExitOnError);
  if (!faHeaderFileChars.empty()) { // ---- headers were read
    std::string faFileCharPtrString(faHeaderFileChars.dataPtr());
    std::istringstream fais(faFileCharPtrString, std::istringstream::in);
    while (!fais.eof()) {
      std::string faHeaderName;
      fais >> faHeaderName;
      if (!fais.eof()) {
        if (faHeaderName.rfind(state_pfx, 0) == 0) {
          return true;
        }
      }
    }
  }
  return false;
}

void
PeleC::restart(amrex::Amr& papa, std::istream& is, bool bReadSpecial)
{
  // Let's check PeleC checkpoint version first;
  // trying to read from checkpoint; if nonexisting, set it to 0.
  if (input_version == -1) {
    if (amrex::ParallelDescriptor::IOProcessor()) {
      std::ifstream PeleCHeaderFile;
      std::string FullPathPeleCHeaderFile = papa.theRestartFile();
      FullPathPeleCHeaderFile += "/PeleCHeader";
      PeleCHeaderFile.open(FullPathPeleCHeaderFile.c_str(), std::ios::in);
      if (PeleCHeaderFile.good()) {
        char foo[256];
        // first line: Checkpoint version: ?
        PeleCHeaderFile.getline(foo, 256, ':');
        PeleCHeaderFile >> input_version;
        PeleCHeaderFile.close();
      } else {
        input_version = 0;
      }
    }
    amrex::ParallelDescriptor::Bcast(
      &input_version, 1, amrex::ParallelDescriptor::IOProcessorNumber());
  }

  AMREX_ASSERT(input_version >= 0);

  // Also need to mod checkPoint function to store the new version in a text
  // file
  AmrLevel::restart(papa, is, bReadSpecial);

  // Deal here with new state descriptor types added, with corresponding
  // input_version > 0, if applicable
  amrex::Vector<int> state_in_checkpoint(desc_lst.size(), 1);
  set_state_in_checkpoint(state_in_checkpoint);
  for (int i = 0; i < desc_lst.size(); ++i) {
    if (state_in_checkpoint[i] == 0) {
      const amrex::Real ctime = state[i - 1].curTime();
      state[i].define(
        geom.Domain(), grids, dmap, desc_lst[i], ctime, parent->dtLevel(level),
        Factory());
      get_new_data(i).setVal(0.0);
    }
  }
  buildMetrics();

  init_eb();

  const amrex::MultiFab& S_new = get_new_data(State_Type);

  for (int n = 0; n < src_list.size(); ++n) {
    int oldGrow = numGrow();
    int newGrow = S_new.nGrow();
    old_sources[src_list[n]] = std::make_unique<amrex::MultiFab>(
      grids, dmap, NVAR, oldGrow, amrex::MFInfo(), Factory());
    new_sources[src_list[n]] = std::make_unique<amrex::MultiFab>(
      grids, dmap, NVAR, newGrow, amrex::MFInfo(), Factory());
  }

  if (do_hydro || do_diffuse) {
    Sborder.define(grids, dmap, NVAR, numGrow(), amrex::MFInfo(), Factory());
  }

  if (!do_mol) {
    if (do_hydro) {
      hydro_source.define(grids, dmap, NVAR, 0, amrex::MFInfo(), Factory());

      // This array holds the sum of all source terms that affect the
      // hydrodynamics. If we are doing the source term predictor, we'll also
      // use this after the hydro update to store the sum of the new-time
      // sources, so that we can compute the time derivative of the source
      // terms.
      sources_for_hydro.define(
        grids, dmap, NVAR, numGrow(), amrex::MFInfo(), Factory());
    }
  } else {
    Sborder.define(grids, dmap, NVAR, numGrow(), amrex::MFInfo(), Factory());
  }

  // get the elapsed CPU time to now;
  if (level == 0 && amrex::ParallelDescriptor::IOProcessor()) {
    // get elapsed CPU time
    std::ifstream CPUFile;
    std::string FullPathCPUFile = parent->theRestartFile();
    FullPathCPUFile += "/CPUtime";
    CPUFile.open(FullPathCPUFile.c_str(), std::ios::in);

    CPUFile >> previousCPUTimeUsed;
    CPUFile.close();

    amrex::Print() << "read CPU time: " << previousCPUTimeUsed << "\n";
  }

  if (track_grid_losses && level == 0) {

    // get the current value of the diagnostic quantities
    std::ifstream DiagFile;
    std::string FullPathDiagFile = parent->theRestartFile();
    FullPathDiagFile += "/Diagnostics";
    DiagFile.open(FullPathDiagFile.c_str(), std::ios::in);

    for (amrex::Real& i : material_lost_through_boundary_cumulative) {
      DiagFile >> i;
    }

    DiagFile.close();
  }

  /* Not implemented for GPU
        if (level == 0)
        {
      // get problem-specific stuff -- note all processors do this,
      // eliminating the need for a broadcast
      std::string dir = parent->theRestartFile();

      char * dir_for_pass = new char[dir.size() + 1];
      std::copy(dir.begin(), dir.end(), dir_for_pass);
      dir_for_pass[dir.size()] = '\0';

      int len = dir.size();

      Vector<int> int_dir_name(len);
      for (int j = 0; j < len; j++)
          int_dir_name[j] = (int) dir_for_pass[j];

      AMREX_FORT_PROC_CALL(PROBLEM_RESTART,problem_restart)(int_dir_name.dataPtr(),
      &len);

      delete [] dir_for_pass;

      }
  */

  if (level > 0 && do_reflux) {
    flux_reg = std::make_unique<amrex::EBFluxRegister>(
      grids, papa.boxArray(level - 1), dmap, papa.DistributionMap(level - 1),
      geom, papa.Geom(level - 1), papa.refRatio(level - 1), level, NVAR);

    if (!amrex::DefaultGeometry().IsCartesian()) {
      // pres_reg.define(
      // grids, papa.boxArray(level - 1), dmap, papa.DistributionMap(level - 1),
      // geom, papa.Geom(level - 1), papa.refRatio(level - 1), level, 1);
      amrex::Abort("We don't do rz.");
    }
  }

  if (input_version > 0 && level == 0 && eb_in_domain) {
    if (amrex::ParallelDescriptor::IOProcessor()) {
      std::ifstream BodyFile;
      std::string FullPathBodyFile = parent->theRestartFile();
      FullPathBodyFile += "/" + body_state_filename;
      BodyFile.open(FullPathBodyFile.c_str(), std::ios::in);
      amrex::FArrayBox bstate_fab;
      bstate_fab.readFrom(BodyFile);
      BodyFile.close();
      if (bstate_fab.nComp() != NVAR) {
        amrex::Abort("Body state incompatible with checkpointed version");
      }
      const auto bx = bstate_fab.box();
      auto const& bstate_arr = bstate_fab.array();
      amrex::Gpu::DeviceVector<amrex::Real> local_body_state(NVAR, -1);
      amrex::Real* p_body_state = local_body_state.begin();
      amrex::ParallelFor(
        bx, NVAR, [=] AMREX_GPU_DEVICE(int i, int j, int k, int n) noexcept {
          p_body_state[n] = bstate_arr(i, j, k, n);
        });

      amrex::Gpu::copy(
        amrex::Gpu::deviceToHost, local_body_state.begin(),
        local_body_state.end(), body_state.begin());
    }
    amrex::ParallelDescriptor::Bcast(
      &(body_state[0]), body_state.size(), // NOLINT
      amrex::ParallelDescriptor::IOProcessorNumber());
    body_state_set = true;
  }
}

void
PeleC::set_state_in_checkpoint(amrex::Vector<int>& state_in_checkpoint)
{
  for (int i = 0; i < num_state_type; ++i) {
    const bool is_present =
      check_state_in_checkpoint(static_cast<StateType>(i));

    if (i == State_Type) {
      state_in_checkpoint[i] = 1;
      if ((!is_present) && (level == 0)) {
        amrex::Abort("State_Type is not present in the checkpoint file");
      }
    } else if (i == Reactions_Type) {
      if (!do_react) {
        state_in_checkpoint[i] = 0;
      } else {
        state_in_checkpoint[i] = is_present ? 1 : 0;
      }
    } else if (i == Work_Estimate_Type) {
      // Never use work estimate checkpoint
      state_in_checkpoint[i] = 0;
    } else {
      amrex::Abort("Unknown StateType");
    }
  }
}

void
PeleC::checkPoint(
  const std::string& dir,
  std::ostream& os,
  amrex::VisMF::How how,
  bool /*dump_old_default*/)
{
  amrex::AmrLevel::checkPoint(dir, os, how, dump_old);

  if (level == 0 && amrex::ParallelDescriptor::IOProcessor()) {
    {
      std::ofstream PeleCHeaderFile;
      std::string FullPathPeleCHeaderFile = dir;
      FullPathPeleCHeaderFile += "/PeleCHeader";
      PeleCHeaderFile.open(FullPathPeleCHeaderFile.c_str(), std::ios::out);

      PeleCHeaderFile << "Checkpoint version: " << current_version << std::endl;
      PeleCHeaderFile.close();
    }

    {
      // store elapsed CPU time
      std::ofstream CPUFile;
      std::string FullPathCPUFile = dir;
      FullPathCPUFile += "/CPUtime";
      CPUFile.open(FullPathCPUFile.c_str(), std::ios::out);

      CPUFile << std::setprecision(15) << getCPUTime();
      CPUFile.close();
    }

    {
      // Store the level at which EB was generated
      std::ofstream EBLevelFile;
      std::string FullPathEBLevelFile = dir;
      FullPathEBLevelFile += "/EBMaxLevel";
      EBLevelFile.open(FullPathEBLevelFile.c_str(), std::ios::out);
      EBLevelFile << eb_max_lvl_gen;
      EBLevelFile.close();
    }

    if (track_grid_losses) {
      // store diagnostic quantities
      std::ofstream DiagFile;
      std::string FullPathDiagFile = dir;
      FullPathDiagFile += "/Diagnostics";
      DiagFile.open(FullPathDiagFile.c_str(), std::ios::out);

      for (amrex::Real i : material_lost_through_boundary_cumulative) {
        DiagFile << std::setprecision(15) << i << std::endl;
      }

      DiagFile.close();
    }

    /* Not implemented for GPU{
            // store any problem-specific stuff
            char * dir_for_pass = new char[dir.size() + 1];
            std::copy(dir.begin(), dir.end(), dir_for_pass);
            dir_for_pass[dir.size()] = '\0';

            int len = dir.size();

            Vector<int> int_dir_name(len);
            for (int j = 0; j < len; j++)
            int_dir_name[j] = (int) dir_for_pass[j];

            AMREX_FORT_PROC_CALL(PROBLEM_CHECKPOINT,problem_checkpoint)(int_dir_name.dataPtr(),
       &len);

            delete [] dir_for_pass;
        }
    */
  }

  if (current_version > 0) {
    if (amrex::ParallelDescriptor::IOProcessor() && eb_in_domain) {
      amrex::IntVect iv(AMREX_D_DECL(0, 0, 0));
      const amrex::Box bx(iv, iv);
      amrex::FArrayBox bstate_fab(bx, NVAR);
      auto const& bstate_arr = bstate_fab.array();
      auto const captured_body_state = body_state;
      amrex::ParallelFor(
        bx, NVAR, [=] AMREX_GPU_DEVICE(int i, int j, int k, int n) noexcept {
          bstate_arr(i, j, k, n) = captured_body_state[n];
        });

      std::ofstream BodyFile;
      std::string FullPathBodyFile = dir;
      FullPathBodyFile += "/" + body_state_filename;
      BodyFile.open(FullPathBodyFile.c_str(), std::ios::out);
      bstate_fab.writeOn(BodyFile);
      BodyFile.close();
    }
  }
}

void
PeleC::setPlotVariables()
{
  amrex::AmrLevel::setPlotVariables();

  amrex::ParmParse pp("pelec");

  bool plot_cost = do_react_load_balance || do_mol_load_balance;
  pp.query("plot_cost", plot_cost);
  if (plot_cost) {
    for (int i = 0; i < desc_lst[Work_Estimate_Type].nComp(); i++) {
      amrex::Amr::addStatePlotVar(desc_lst[Work_Estimate_Type].name(i));
    }
  } else {
    for (int i = 0; i < desc_lst[Work_Estimate_Type].nComp(); i++) {
      amrex::Amr::deleteStatePlotVar(desc_lst[Work_Estimate_Type].name(i));
    }
  }

  if (!do_react) {
    for (int i = 0; i < desc_lst[Reactions_Type].nComp(); i++) {
      amrex::Amr::deleteStatePlotVar(desc_lst[Reactions_Type].name(i));
    }
  }

  bool plot_rhoy = true;
  pp.query("plot_rhoy", plot_rhoy);
  if (plot_rhoy) {
    for (int i = 0; i < NUM_SPECIES; i++) {
      amrex::Amr::addStatePlotVar(desc_lst[State_Type].name(FirstSpec + i));
    }
  } else {
    for (int i = 0; i < NUM_SPECIES; i++) {
      amrex::Amr::deleteStatePlotVar(desc_lst[State_Type].name(FirstSpec + i));
    }
  }

  bool plot_massfrac = false;
  pp.query("plot_massfrac", plot_massfrac);
  if (plot_massfrac) {
    amrex::Amr::addDerivePlotVar("massfrac");
  } else {
    amrex::Amr::deleteDerivePlotVar("massfrac");
  }

#ifdef PELEC_USE_PLASMA
  if (plot_numdens) {
    amrex::Amr::addDerivePlotVar("numdens");
  } else {
    amrex::Amr::deleteDerivePlotVar("numdens");
  }
#endif
  bool plot_rho_adv = true;
  pp.query("plot_rho_adv", plot_rho_adv);
  if (plot_rho_adv) {
    for (int i = 0; i < NUM_ADV; i++) {
      amrex::Amr::addStatePlotVar(desc_lst[State_Type].name(FirstAdv + i));
    }
  } else {
    for (int i = 0; i < NUM_ADV; i++) {
      amrex::Amr::deleteStatePlotVar(desc_lst[State_Type].name(FirstAdv + i));
    }
  }

  bool plot_adv = false;
  pp.query("plot_adv", plot_adv);
  if (plot_adv) {
    amrex::Amr::addDerivePlotVar("adv");
  } else {
    amrex::Amr::deleteDerivePlotVar("adv");
  }

  bool plot_moleFrac = false;
  pp.query("plot_molefrac", plot_moleFrac);
  if (plot_moleFrac) {
    amrex::Amr::addDerivePlotVar("molefrac");
  } else {
    amrex::Amr::deleteDerivePlotVar("molefrac");
  }
}

void
PeleC::writePlotFilePost(const std::string& dir, std::ostream& /*os*/)
{
  if (level == 0 && amrex::ParallelDescriptor::IOProcessor()) {
    writeJobInfo(dir);
  }
}

void
PeleC::writeJobInfo(const std::string& dir)
{
  // job_info file with details about the run
  std::ofstream jobInfoFile;
  std::string FullPathJobInfoFile = dir;
  FullPathJobInfoFile += "/job_info";
  jobInfoFile.open(FullPathJobInfoFile.c_str(), std::ios::out);

  std::string PrettyLine = "==================================================="
                           "============================\n";
  std::string OtherLine = "----------------------------------------------------"
                          "----------------------------\n";
  std::string SkipSpace = "        ";

  // job information
  jobInfoFile << PrettyLine;
  jobInfoFile << " PeleC Job Information\n";
  jobInfoFile << PrettyLine;

  jobInfoFile << "job name: " << job_name << "\n\n";
  jobInfoFile << "inputs file: " << inputs_name << "\n\n";

  jobInfoFile << "number of MPI processes: "
              << amrex::ParallelDescriptor::NProcs() << "\n";
#ifdef AMREX_USE_OMP
  jobInfoFile << "number of threads:       " << omp_get_max_threads() << "\n";
#endif

  jobInfoFile << "\n";
  jobInfoFile << "CPU time used since start of simulation (CPU-hours): "
              << getCPUTime() / 3600.0;

  jobInfoFile << "\n\n";

  // plotfile information
  jobInfoFile << PrettyLine;
  jobInfoFile << " Plotfile Information\n";
  jobInfoFile << PrettyLine;

  time_t now = time(nullptr);

  // Convert now to tm struct for local timezone
  char time_buffer[128];
  const tm* localtm = localtime(&now);
  strftime(time_buffer, sizeof(time_buffer), "%b %d %Y %H:%M:%S", localtm);
  jobInfoFile << "output data / time: " << time_buffer << std::endl;

  std::string currentDir = amrex::FileSystem::CurrentPath();
  jobInfoFile << "output dir:         " << currentDir << "\n";

  jobInfoFile << "\n\n";

  // build information
  jobInfoFile << PrettyLine;
  jobInfoFile << " Build Information\n";
  jobInfoFile << PrettyLine;

  jobInfoFile << "build date:    " << amrex::buildInfoGetBuildDate() << "\n";
  jobInfoFile << "build machine: " << amrex::buildInfoGetBuildMachine() << "\n";
  jobInfoFile << "build dir:     " << amrex::buildInfoGetBuildDir() << "\n";
  jobInfoFile << "AMReX dir:     " << amrex::buildInfoGetAMReXDir() << "\n";

  jobInfoFile << "\n";

  jobInfoFile << "COMP:          " << amrex::buildInfoGetComp() << "\n";
  jobInfoFile << "COMP version:  " << amrex::buildInfoGetCompVersion() << "\n";
  jobInfoFile << "FCOMP:         " << amrex::buildInfoGetFcomp() << "\n";
  jobInfoFile << "FCOMP version: " << amrex::buildInfoGetFcompVersion() << "\n";

  jobInfoFile << "\n";

  for (int n = 1; n <= amrex::buildInfoGetNumModules(); n++) {
    jobInfoFile << amrex::buildInfoGetModuleName(n) << ": "
                << amrex::buildInfoGetModuleVal(n) << "\n";
  }

  jobInfoFile << "\n";

  const char* githash1 = amrex::buildInfoGetGitHash(1);
  const char* githash2 = amrex::buildInfoGetGitHash(2);
  const char* githash3 = amrex::buildInfoGetGitHash(3);
  const char* githash4 = amrex::buildInfoGetGitHash(4);
  const char* githash5 = amrex::buildInfoGetGitHash(5);
  if (strlen(githash1) > 0) {
    jobInfoFile << "PeleC       git hash: " << githash1 << "\n";
  }
  if (strlen(githash2) > 0) {
    jobInfoFile << "AMReX       git hash: " << githash2 << "\n";
  }
  if (strlen(githash3) > 0) {
    jobInfoFile << "PelePhysics git hash: " << githash3 << "\n";
  }
  if (strlen(githash4) > 0) {
    jobInfoFile << "AMReX-Hydro git hash: " << githash4 << "\n";
  }
  if (strlen(githash5) > 0) {
    jobInfoFile << "SUNDIALS    git hash: " << githash5 << "\n";
  }

  const char* buildgithash = amrex::buildInfoGetBuildGitHash();
  const char* buildgitname = amrex::buildInfoGetBuildGitName();
  if (strlen(buildgithash) > 0) {
    jobInfoFile << buildgitname << " git hash: " << buildgithash << "\n";
  }

  jobInfoFile << "\n\n";

  // grid information
  jobInfoFile << PrettyLine;
  jobInfoFile << " Grid Information\n";
  jobInfoFile << PrettyLine;

  int f_lev = parent->finestLevel();

  for (int i = 0; i <= f_lev; i++) {
    jobInfoFile << " level: " << i << "\n";
    jobInfoFile << "   number of boxes = " << parent->numGrids(i) << "\n";
    jobInfoFile << "   maximum zones   = ";
    for (int n = 0; n < AMREX_SPACEDIM; n++) {
      jobInfoFile << parent->Geom(i).Domain().length(n) << " ";
      // jobInfoFile << parent->Geom(i).ProbHi(n) << " ";
    }
    jobInfoFile << "\n\n";
  }

  jobInfoFile << " Boundary conditions\n";
  amrex::Vector<std::string> lo_bc_out(AMREX_SPACEDIM);
  amrex::Vector<std::string> hi_bc_out(AMREX_SPACEDIM);
  amrex::ParmParse pp("pelec");
  pp.getarr("lo_bc", lo_bc_out, 0, AMREX_SPACEDIM);
  pp.getarr("hi_bc", hi_bc_out, 0, AMREX_SPACEDIM);

  // these names correspond to the integer flags setup in the
  // Setup.cpp

  jobInfoFile << "   -x: " << lo_bc_out[0] << "\n";
  jobInfoFile << "   +x: " << hi_bc_out[0] << "\n";
  if (AMREX_SPACEDIM >= 2) {
    jobInfoFile << "   -y: " << lo_bc_out[1] << "\n";
    jobInfoFile << "   +y: " << hi_bc_out[1] << "\n";
  }
  if (AMREX_SPACEDIM == 3) {
    jobInfoFile << "   -z: " << lo_bc_out[2] << "\n";
    jobInfoFile << "   +z: " << hi_bc_out[2] << "\n";
  }

  jobInfoFile << "\n\n";

  const int mlen = 20;

  jobInfoFile << PrettyLine;
  jobInfoFile << " Species Information\n";
  jobInfoFile << PrettyLine;

  jobInfoFile << std::setw(6) << "index" << SkipSpace << std::setw(mlen + 1)
              << "name" << SkipSpace << std::setw(7) << "A" << SkipSpace
              << std::setw(7) << "Z"
              << "\n";
  jobInfoFile << OtherLine;
  jobInfoFile << "\n\n";

  // runtime parameters
  jobInfoFile << PrettyLine;
  jobInfoFile << " Inputs File Parameters\n";
  jobInfoFile << PrettyLine;

  amrex::ParmParse::dumpTable(jobInfoFile, true);
  jobInfoFile.close();
}

// PeleC::writeBuildInfo
// Similar to writeJobInfo, but the subset of information that makes sense
// without an input file to enable --describe in format similar to CASTRO
void
PeleC::writeBuildInfo(std::ostream& os)
{
  std::string PrettyLine = std::string(78, '=') + "\n";
  // std::string OtherLine = std::string(78, '-') + "\n";
  // std::string SkipSpace = std::string(8, ' ');

  // build information
  os << PrettyLine;
  os << " PeleC Build Information\n";
  os << PrettyLine;

  os << "build date:    " << amrex::buildInfoGetBuildDate() << "\n";
  os << "build machine: " << amrex::buildInfoGetBuildMachine() << "\n";
  os << "build dir:     " << amrex::buildInfoGetBuildDir() << "\n";
  os << "AMReX dir:     " << amrex::buildInfoGetAMReXDir() << "\n";

  os << "\n";

  os << "COMP:          " << amrex::buildInfoGetComp() << "\n";
  os << "COMP version:  " << amrex::buildInfoGetCompVersion() << "\n";

  amrex::Print() << "C++ compiler:  " << amrex::buildInfoGetCXXName() << "\n";
  amrex::Print() << "C++ flags:     " << amrex::buildInfoGetCXXFlags() << "\n";

  os << "\n";

  os << "FCOMP:         " << amrex::buildInfoGetFcomp() << "\n";
  os << "FCOMP version: " << amrex::buildInfoGetFcompVersion() << "\n";

  os << "\n";

  amrex::Print() << "Link flags:    " << amrex::buildInfoGetLinkFlags() << "\n";
  amrex::Print() << "Libraries:     " << amrex::buildInfoGetLibraries() << "\n";

  os << "\n";

  for (int n = 1; n <= amrex::buildInfoGetNumModules(); n++) {
    os << amrex::buildInfoGetModuleName(n) << ": "
       << amrex::buildInfoGetModuleVal(n) << "\n";
  }

  os << "\n";
  const char* githash1 = amrex::buildInfoGetGitHash(1);
  const char* githash2 = amrex::buildInfoGetGitHash(2);
  const char* githash3 = amrex::buildInfoGetGitHash(3);
  const char* githash4 = amrex::buildInfoGetGitHash(4);
  const char* githash5 = amrex::buildInfoGetGitHash(5);
  if (strlen(githash1) > 0) {
    os << "PeleC       git hash: " << githash1 << "\n";
  }
  if (strlen(githash2) > 0) {
    os << "AMReX       git hash: " << githash2 << "\n";
  }
  if (strlen(githash3) > 0) {
    os << "PelePhysics git hash: " << githash3 << "\n";
  }
  if (strlen(githash4) > 0) {
    os << "AMReX-Hydro git hash: " << githash4 << "\n";
  }
  if (strlen(githash5) > 0) {
    os << "SUNDIALS    git hash: " << githash5 << "\n";
  }

  const char* buildgithash = amrex::buildInfoGetBuildGitHash();
  const char* buildgitname = amrex::buildInfoGetBuildGitName();
  if (strlen(buildgithash) > 0) {
    os << buildgitname << " git hash: " << buildgithash << "\n";
  }

  os << "\n";
  os << " PeleC Compile time variables: \n";

  int mm;
  int kk;
  int ii;
  int nfit;
  CKINDX(&mm, &kk, &ii, &nfit);
  os << std::setw(40) << std::left << "Number elements from chem cpp : " << mm
     << std::endl;
  os << std::setw(40) << std::left << "Number species from chem cpp : " << kk
     << std::endl;
  os << std::setw(40) << std::left << "Number reactions from chem cpp : " << ii
     << std::endl;

  os << "\n";
  os << " PeleC Defines: \n";
#ifdef AMREX_USE_OMP
  os << std::setw(35) << std::left << "AMREX_USE_OMP " << std::setw(6) << "ON"
     << std::endl;
#else
  os << std::setw(35) << std::left << "AMREX_USE_OMP " << std::setw(6) << "OFF"
     << std::endl;
#endif

#ifdef MPI_VERSION
  os << std::setw(35) << std::left << "MPI_VERSION " << std::setw(6)
     << MPI_VERSION << std::endl;
#else
  os << std::setw(35) << std::left << "MPI_VERSION " << std::setw(6)
     << "UNDEFINED" << std::endl;
#endif

#ifdef MPI_SUBVERSION
  os << std::setw(35) << std::left << "MPI_SUBVERSION " << std::setw(6)
     << MPI_SUBVERSION << std::endl;
#else
  os << std::setw(35) << std::left << "MPI_SUBVERSION " << std::setw(6)
     << "UNDEFINED" << std::endl;
#endif

  os << std::setw(35) << std::left << "NUM_ADV=" << NUM_ADV << std::endl;

  os << std::setw(35) << std::left << "NUM_AUX=" << NUM_AUX << std::endl;

  os << std::setw(35) << std::left << "NUM_LIN=" << NUM_LIN << std::endl;

#ifdef PELEC_USE_MASA
  os << std::setw(35) << std::left << "PELEC_USE_MASA " << std::setw(6) << "ON"
     << std::endl;
#else
  os << std::setw(35) << std::left << "PELEC_USE_MASA " << std::setw(6) << "OFF"
     << std::endl;
#endif

#ifdef PELEC_SPRAY
  os << std::setw(35) << std::left << "PELEC_SPRAY " << std::setw(6) << "ON"
     << std::endl;
#else
  os << std::setw(35) << std::left << "PELEC_SPRAY " << std::setw(6) << "OFF"
     << std::endl;
#endif

  os << "\n\n";
}

void
PeleC::initLevelDataFromPlt(
  const int lev, const std::string& dataPltFile, amrex::MultiFab& S_new)
{
  amrex::Print() << "Using data (rho, u, T, Y) from pltfile " << dataPltFile
                 << std::endl;
  pele::physics::pltfilemanager::PltFileManager pltData(dataPltFile);
  const auto plt_vars = pltData.getVariableList();

  // Read rho, u, temperature (required)
  std::map<std::string, int> vars{
    {"density", -1}, {"x_velocity", -1}, {"Temp", -1}};
  for (auto& var : vars) {
    var.second = find_position(plt_vars, var.first);
    if (var.second == -1) {
      amrex::Abort("Unable to find variable in plot file: " + var.first);
    }
  }
  pltData.fillPatchFromPlt(lev, geom, vars["density"], URHO, 1, S_new);
  pltData.fillPatchFromPlt(
    lev, geom, vars["x_velocity"], UMX, AMREX_SPACEDIM, S_new);
  pltData.fillPatchFromPlt(lev, geom, vars["Temp"], UTEMP, 1, S_new);

  // Copy species from the plot file
  for (int n = 0; n < spec_names.size(); n++) {
    const auto& spec = spec_names.at(n);
    const int pos = find_position(plt_vars, "Y(" + spec + ")");
    if (pos != -1) {
      pltData.fillPatchFromPlt(lev, geom, pos, UFS + n, 1, S_new);
    }
  }

  // Sanity check the species, clean them up if they aren't too bad
  auto sarrs = S_new.arrays();
  const auto tol = init_pltfile_massfrac_tol;
  amrex::ParallelFor(
    S_new, [=] AMREX_GPU_DEVICE(int nbx, int i, int j, int k) noexcept {
      auto sarr = sarrs[nbx];
      amrex::Real sumY = 0.0;

      for (int n = 0; n < NUM_SPECIES; n++) {
        // if the species is not too far out of bounds, clip it
        const auto mf = sarr(i, j, k, UFS + n);
        if ((mf < 0.0) || (1.0 < mf)) {
          if (((-tol < mf) && (mf < 0.0)) || ((1.0 < mf) && (mf < 1 + tol))) {
            sarr(i, j, k, UFS + n) =
              amrex::min<amrex::Real>(1.0, amrex::max<amrex::Real>(0.0, mf));
          } else {
#ifdef AMREX_USE_GPU
            AMREX_DEVICE_PRINTF(
              "Species mass fraction is out of bounds (spec, value): (%d, %g)",
              n, mf);
            amrex::Abort();
#else
            amrex::Abort(
              "Species mass fraction is out of bounds (spec, value): ( " +
              std::to_string(n) + ", " + std::to_string(mf) + ")");
#endif
          }
        }

        sumY += sarr(i, j, k, UFS + n);
      }

      // If the sumY isn't too far from 1, renormalize
      if (amrex::Math::abs(1.0 - sumY) < tol) {
        for (int n = 0; n < NUM_SPECIES; n++) {
          sarr(i, j, k, UFS + n) /= sumY;
        }
      } else {
#ifdef AMREX_USE_GPU
        AMREX_DEVICE_PRINTF(
          "Species mass fraction don't sum to 1. The sum is: %g", sumY);
        amrex::Abort();
#else
        amrex::Abort(
          "Species mass fraction don't sum to 1. The sum is: " +
          std::to_string(sumY));
#endif
      }
    });
  amrex::Gpu::synchronize();

  // Convert to conserved variables
  amrex::ParallelFor(
    S_new, [=] AMREX_GPU_DEVICE(int nbx, int i, int j, int k) noexcept {
      auto sarr = sarrs[nbx];
      const amrex::Real rho = sarr(i, j, k, URHO);
      const amrex::Real temp = sarr(i, j, k, UTEMP);
      amrex::Real massfrac[NUM_SPECIES] = {0.0};
      for (int n = 0; n < NUM_SPECIES; n++) {
        massfrac[n] = sarr(i, j, k, UFS + n);
        sarr(i, j, k, UFS + n) *= rho;
      }
      AMREX_D_TERM(sarr(i, j, k, UMX) *= rho;, sarr(i, j, k, UMY) *= rho;
                   , sarr(i, j, k, UMZ) *= rho;)

      auto eos = pele::physics::PhysicsType::eos();
      amrex::Real eint = 0.0;
      eos.RTY2E(rho, temp, massfrac, eint);

      sarr(i, j, k, UEINT) = rho * eint;
      sarr(i, j, k, UEDEN) =
        rho * eint + 0.5 *
                       (AMREX_D_TERM(
                         sarr(i, j, k, UMX) * sarr(i, j, k, UMX),
                         +sarr(i, j, k, UMY) * sarr(i, j, k, UMY),
                         +sarr(i, j, k, UMZ) * sarr(i, j, k, UMZ))) /
                       rho;
    });
  amrex::Gpu::synchronize();
}

void PeleC::writeDebugPlotFile(const amrex::Vector<const amrex::MultiFab*> &a_MF,
                               const std::string &pltname,
                               int firstLevel,
                               int firstComp,
                               int nComp)
{
   // Component and level sizes
   AMREX_ASSERT(a_MF[0]->nComp() >= firstComp+nComp);
   AMREX_ASSERT(parent->finestLevel() >= firstLevel + a_MF.size());

   // Generate dumb names
   amrex::Vector<std::string> names(nComp);
   for (int n = 0; n < nComp; n++) {
      names[n] = "comp"+std::to_string(n);
   }

   // Dumb level steps
   amrex::Vector<int> istep(a_MF.size(), 0);

   // Make a vector of aliases with required components
   amrex::Vector<amrex::MultiFab> aliases;
   for (int lev = 0; lev < a_MF.size(); lev++ ) {
      aliases.emplace_back(*a_MF[lev],amrex::make_alias,firstComp,nComp);
   }

   // Vector of geometries/ref_ratios
   amrex::Vector<amrex::Geometry> Geoms(a_MF.size());
   amrex::Vector<amrex::IntVect> RefRatios(a_MF.size());
   for (int lev = 0; lev < a_MF.size(); lev++ ) {
      Geoms[lev] = parent->Geom(firstLevel+lev);
      RefRatios[lev] = {AMREX_D_DECL(2,2,2)};
   }

   amrex::WriteMultiLevelPlotfile(pltname, a_MF.size(), GetVecOfConstPtrs(aliases),
                                  names, Geoms, 0.0, istep, RefRatios);
}

#ifdef PELEC_USE_PLASMA
void PeleC::writeMonitorFile(amrex::MultiFab& S, const amrex::Real *mwt, amrex::Real dt, amrex::Real time, int i){

  BL_PROFILE("PeleC::writeMonitorFile()");

  // ndeak addition - create monitor files for each level
  // Monitor file should output the following
  //    - Min and max n_E, n_O4+, n_O2-
  //    - Min and max phi, E/N
  //    - Min and max electron diffusivity and mobility coefs
  //    - dx and other relevant grid info
  //    - CFL and diffusion stability criteria
  // Variables used in monitor file claculations
  
  // FIXME: Monitor file output currently a total mess, basically currently hard-coding output for each mechanism being considered
  // Should add way for user to specify desired species in input file rather than hard-coding

  amrex::Real NA = 6.0221409e23; // 1/mol
  const amrex::Real* dx = geom.CellSize();

  amrex::Real min_nE = 0.0;
  amrex::Real max_nE = 0.0;
  amrex::Real flux_curr = 0.0;

  if(pac_mechanism){
    // Sum variables
    int finest_level = parent->finestLevel();
    bool local_flag = true;
    amrex::Real mO = 0.0;
    amrex::Real mOH = 0.0;
    amrex::Real mH = 0.0;
    amrex::Real mN2vib = 0.0;
    amrex::Real mN2ele = 0.0;
    amrex::Real mO2ele = 0.0;
    amrex::Real mO2p = 0.0;
    amrex::Real mN2p = 0.0;
    amrex::Real mO2m = 0.0;
    amrex::Real mOm = 0.0;
    amrex::Real mCO = 0.0;
    amrex::Real mCO2 = 0.0;
    amrex::Real mC2H4 = 0.0;
    amrex::Real tot_E = 0.0;

    // Perform integrals over key quantities if at finest level
    if(level == finest_level) {
      for (int lev = 0; lev <= finest_level; lev++) {
        PeleC& pc_lev = getLevel(lev);

        mO += pc_lev.volWgtSum("rho_O", time, local_flag);
        mOH += pc_lev.volWgtSum("rho_OH", time, local_flag);
        mH += pc_lev.volWgtSum("rho_H", time, local_flag);
        mN2vib += (pc_lev.volWgtSum("rho_N2(v1)", time, local_flag) + pc_lev.volWgtSum("rho_N2(v2)", time, local_flag) + pc_lev.volWgtSum("rho_N2(v3)", time, local_flag) + pc_lev.volWgtSum("rho_N2(v4)", time, local_flag) + pc_lev.volWgtSum("rho_N2(v5)", time, local_flag));
        mN2ele += (pc_lev.volWgtSum("rho_N2(A3Sigma)", time, local_flag) + pc_lev.volWgtSum("rho_N2(B3Pi)", time, local_flag) + pc_lev.volWgtSum("rho_N2(C3Pi)", time, local_flag));
        mO2ele += (pc_lev.volWgtSum("rho_O2(a1Delta)", time, local_flag) + pc_lev.volWgtSum("rho_O2(b1Sigma)", time, local_flag));
        mO2p += pc_lev.volWgtSum("rho_O2+", time, local_flag);
        mN2p += pc_lev.volWgtSum("rho_N2+", time, local_flag); 
        if(pac_mechanism >= 2){
          mO2m += pc_lev.volWgtSum("rho_O2-", time, local_flag);
          mOm += pc_lev.volWgtSum("rho_O-", time, local_flag);
        }
        mCO += pc_lev.volWgtSum("rho_CO", time, local_flag);
        mCO2 += pc_lev.volWgtSum("rho_CO2", time, local_flag);
        mC2H4 += pc_lev.volWgtSum("rho_C2H4", time, local_flag);
        tot_E += pc_lev.volWgtSum("rho_e", time, local_flag);
      }

      // Sum across processors
      const int nfoo = 14;
      amrex::Real foo[nfoo] = {mO, mOH, mH, mN2vib, mN2ele, mO2ele, mO2p, mN2p, mO2m, mOm, mCO, mCO2, mC2H4, tot_E};
      amrex::ParallelDescriptor::ReduceRealSum(foo, nfoo, amrex::ParallelDescriptor::IOProcessorNumber());

      // Reassign sum values
      int i = 0;
      mO = foo[i++];
      mOH = foo[i++];
      mH = foo[i++];
      mN2vib = foo[i++];
      mN2ele = foo[i++];
      mO2ele = foo[i++];
      mO2p = foo[i++];
      mN2p = foo[i++];
      mO2m = foo[i++];
      mOm = foo[i++];
      mCO = foo[i++];
      mCO2 = foo[i++];
      mC2H4 = foo[i++];
      tot_E = foo[i++];
    }

    amrex::Real max_EN = redEfield.max(0, 0, false);
#ifdef PELEC_USE_TWO_TEMP
    amrex::Real max_Te = S.max(UFX+6, 0, false); max_Te *= (1.0/11595.0);
#else
    amrex::Real max_Te; ExtrapTe(max_EN, &max_Te); max_Te *= (1.0/11595.0);
#endif
    amrex::Real max_Tg = S.max(UTEMP, 0, false);
    amrex::Real max_nE = S.max(UFS+E_ID, 0, false) * (1.0/mwt[E_ID]) * NA;
    amrex::Real max_nO = S.max(UFS+3, 0, false) * (1.0/mwt[3]) * NA;
    amrex::Real max_nOH = S.max(UFS+5, 0, false) * (1.0/mwt[5]) * NA;
    amrex::Real max_nH = S.max(UFS+1, 0, false) * (1.0/mwt[1]) * NA;
    amrex::Real max_nN2vib = S.max(UFS+40, 0, false)* (1.0/mwt[40]) * NA + S.max(UFS+41, 0, false)* (1.0/mwt[41]) * NA + S.max(UFS+42, 0, false)* (1.0/mwt[42]) * NA + S.max(UFS+43, 0, false)* (1.0/mwt[43]) * NA + S.max(UFS+44, 0, false)* (1.0/mwt[44]) * NA;
    amrex::Real max_nN2ele = S.max(UFS+45, 0, false)* (1.0/mwt[45]) * NA + S.max(UFS+46, 0, false)* (1.0/mwt[46]) * NA + S.max(UFS+47, 0, false)* (1.0/mwt[47]) * NA;
    amrex::Real max_nO2ele = S.max(UFS+49, 0, false)* (1.0/mwt[49]) * NA + S.max(UFS+50, 0, false)* (1.0/mwt[50]) * NA;
    amrex::Real max_nO2p = S.max(UFS+51, 0, false)* (1.0/mwt[51]) * NA;
    amrex::Real max_nN2p = S.max(UFS+48, 0, false)* (1.0/mwt[48]) * NA;
    amrex::Real max_nO2m = 0.0;
    amrex::Real max_nOm = 0.0;
    if(pac_mechanism >= 2){
      max_nO2m = S.max(UFS+55, 0, false)* (1.0/mwt[55]) * NA;
      max_nOm = S.max(UFS+56, 0, false)* (1.0/mwt[56]) * NA;
    }
    amrex::Real max_nCO = S.max(UFS+10, 0, false) * (1.0/mwt[10]) * NA;
    amrex::Real max_nCO2 = S.max(UFS+11, 0, false) * (1.0/mwt[11]) * NA;
    amrex::Real max_nC2H4 = S.max(UFS+21, 0, false) * (1.0/mwt[21]) * NA;
  
    if (amrex::ParallelDescriptor::IOProcessor()) {
      std::string baseName = "MonitorFile_Level";
      std::string datString = ".dat";
      std::string intString = std::to_string(i);
      std::string monitorFileName = (baseName + intString + datString);

      std::ofstream MonitorFile;
      MonitorFile.open(monitorFileName.c_str(), std::ios::out | std::ios::app);
      MonitorFile << time << "\t" << max_EN  << "\t" << max_Te  << "\t" << max_Tg  << "\t" << max_nE  << "\t" << max_nO  << "\t" << max_nOH  << "\t" << max_nH  << "\t" << max_nN2vib << "\t" << max_nN2ele  << "\t" << max_nO2ele  << "\t" << max_nO2p << "\t" << max_nN2p << "\t" << max_nO2m  << "\t" << max_nOm << "\t" << max_nCO  << "\t" << max_nCO2 << "\t "<< max_nC2H4 << "\t" << mO << "\t" << mOH << "\t" << mH << "\t" << mN2vib << "\t" << mN2ele << "\t" << mO2ele << "\t" << mO2p << "\t" << mN2p << "\t" << mO2m << "\t" << mOm << "\t" << mCO << "\t" << mCO2 << "\t" << mC2H4 << "\t" << tot_E << "\t" <<dt << std::endl;
      MonitorFile.close();
    }
  }
  else if(airTT_mechanism){
    // Sum variables
    int finest_level = parent->finestLevel();
    bool local_flag = true;
    amrex::Real mO = 0.0;
    amrex::Real mN2vib = 0.0;
    amrex::Real mN2ele = 0.0;
    amrex::Real mO2ele = 0.0;
    amrex::Real mO2p = 0.0;
    amrex::Real mN2p = 0.0;
    amrex::Real mO2m = 0.0;
    amrex::Real mOm = 0.0;
    amrex::Real tot_E = 0.0;

    // Perform integrals over key quantities if at finest level
    if(level == finest_level) {
      for (int lev = 0; lev <= finest_level; lev++) {
        PeleC& pc_lev = getLevel(lev);

        mO += pc_lev.volWgtSum("rho_O", time, local_flag);
        mN2vib += (pc_lev.volWgtSum("rho_N2(v1)", time, local_flag) + pc_lev.volWgtSum("rho_N2(v2)", time, local_flag) + pc_lev.volWgtSum("rho_N2(v3)", time, local_flag) + pc_lev.volWgtSum("rho_N2(v4)", time, local_flag) + pc_lev.volWgtSum("rho_N2(v5)", time, local_flag));
        mN2ele += (pc_lev.volWgtSum("rho_N2(A3Sigma)", time, local_flag) + pc_lev.volWgtSum("rho_N2(B3Pi)", time, local_flag) + pc_lev.volWgtSum("rho_N2(C3Pi)", time, local_flag));
        mO2ele += (pc_lev.volWgtSum("rho_O2(a1Delta)", time, local_flag) + pc_lev.volWgtSum("rho_O2(b1Sigma)", time, local_flag));
        mO2p += pc_lev.volWgtSum("rho_O2+", time, local_flag);
        mN2p += pc_lev.volWgtSum("rho_N2+", time, local_flag); 
        mO2m += pc_lev.volWgtSum("rho_O2-", time, local_flag);
        mOm += pc_lev.volWgtSum("rho_O-", time, local_flag);
        tot_E += pc_lev.volWgtSum("rho_e", time, local_flag);
      }

      // Sum across processors
      const int nfoo = 9;
      amrex::Real foo[nfoo] = {mO, mN2vib, mN2ele, mO2ele, mO2p, mN2p, mO2m, mOm, tot_E};
      amrex::ParallelDescriptor::ReduceRealSum(foo, nfoo, amrex::ParallelDescriptor::IOProcessorNumber());

      // Reassign sum values
      int i = 0;
      mO = foo[i++];
      mN2vib = foo[i++];
      mN2ele = foo[i++];
      mO2ele = foo[i++];
      mO2p = foo[i++];
      mN2p = foo[i++];
      mO2m = foo[i++];
      mOm = foo[i++];
      tot_E = foo[i++];
    }

    amrex::Real max_EN = redEfield.max(0, 0, false);
#ifdef PELEC_USE_TWO_TEMP
    amrex::Real max_Te = S.max(UFX+6, 0, false); max_Te *= (1.0/11595.0);
#else
    amrex::Real max_Te; ExtrapTe(max_EN, &max_Te); max_Te *= (1.0/11595.0);
#endif
    amrex::Real max_Tg = S.max(UTEMP, 0, false);
    amrex::Real max_nE = S.max(UFS+E_ID, 0, false) * (1.0/mwt[E_ID]) * NA;
    amrex::Real max_nO = S.max(UFS+1, 0, false) * (1.0/mwt[1]) * NA;
    amrex::Real max_nN2vib = S.max(UFS+4, 0, false)* (1.0/mwt[4]) * NA + S.max(UFS+5, 0, false)* (1.0/mwt[5]) * NA + S.max(UFS+6, 0, false)* (1.0/mwt[6]) * NA + S.max(UFS+7, 0, false)* (1.0/mwt[7]) * NA + S.max(UFS+8, 0, false)* (1.0/mwt[8]) * NA;
    amrex::Real max_nN2ele = S.max(UFS+9, 0, false)* (1.0/mwt[9]) * NA + S.max(UFS+10, 0, false)* (1.0/mwt[10]) * NA + S.max(UFS+11, 0, false)* (1.0/mwt[11]) * NA;
    amrex::Real max_nO2ele = S.max(UFS+13, 0, false)* (1.0/mwt[13]) * NA + S.max(UFS+14, 0, false)* (1.0/mwt[14]) * NA;
    amrex::Real max_nO2p = S.max(UFS+15, 0, false)* (1.0/mwt[15]) * NA;
    amrex::Real max_nN2p = S.max(UFS+12, 0, false)* (1.0/mwt[12]) * NA;
    amrex::Real max_nO2m = S.max(UFS+19, 0, false)* (1.0/mwt[19]) * NA;
    amrex::Real max_nOm = S.max(UFS+20, 0, false)* (1.0/mwt[20]) * NA;
  
    if (amrex::ParallelDescriptor::IOProcessor()) {
      std::string baseName = "MonitorFile_Level";
      std::string datString = ".dat";
      std::string intString = std::to_string(i);
      std::string monitorFileName = (baseName + intString + datString);

      std::ofstream MonitorFile;
      MonitorFile.open(monitorFileName.c_str(), std::ios::out | std::ios::app);
      MonitorFile << time << "\t" << max_EN  << "\t" << max_Te  << "\t" << max_Tg  << "\t" << max_nE  << "\t" << max_nO << "\t" << max_nN2vib << "\t" << max_nN2ele  << "\t" << max_nO2ele  << "\t" << max_nO2p << "\t" << max_nN2p << "\t" << max_nO2m  << "\t" << max_nOm << "\t" << mO << "\t" << mN2vib << "\t" << mN2ele << "\t" << mO2ele << "\t" << mO2p << "\t" << mN2p << "\t" << mO2m << "\t" << mOm << "\t" << tot_E << "\t" <<dt << std::endl;
      MonitorFile.close();
    }
  }
  else{
    
    int finest_level = parent->finestLevel();
    bool local_flag = true;
    amrex::Real mcations = 0.0;
    amrex::Real manions = 0.0;
    amrex::Real tot_E = 0.0;
    if(!streamer_test){
      if(level == finest_level) {
        for (int lev = 0; lev <= finest_level; lev++) {
          PeleC& pc_lev = getLevel(lev);

          mcations += (pc_lev.volWgtSum("rho_O2+", time, local_flag) + pc_lev.volWgtSum("rho_N2+", time, local_flag) + pc_lev.volWgtSum("rho_O4+", time, local_flag) + pc_lev.volWgtSum("rho_N4+", time, local_flag) + pc_lev.volWgtSum("rho_O2pN2", time, local_flag));
          manions += pc_lev.volWgtSum("rho_O2-", time, local_flag);
          tot_E += pc_lev.volWgtSum("rho_e", time, local_flag);
        }

        // Sum across processors
        const int nfoo = 3;
        amrex::Real foo[nfoo] = {mcations, manions, tot_E};
        amrex::ParallelDescriptor::ReduceRealSum(foo, nfoo, amrex::ParallelDescriptor::IOProcessorNumber());

        // Reassign sum values
        int i = 0;
        mcations = foo[i++];
        manions = foo[i++];
        tot_E = foo[i++];
      }
    }

    if(ef_use_NLsolve || ef_use_nEimplicit){
      min_nE = S.min(UFX + 1, 0, false);
      max_nE = S.max(UFX + 1, 0, false);
    }
    else{
      min_nE = S.min(UFS + E_ID, 0, false) * (1.0/mwt[E_ID]) * NA;
      max_nE = S.max(UFS + E_ID, 0, false) * (1.0/mwt[E_ID]) * NA;
    }
    amrex::Real max_Tg = S.max(UTEMP, 0, false);
    amrex::Real min_nO4p = S.min(UFS + 3, 0, false) * (1.0/mwt[3]) * NA;
    amrex::Real max_nO4p = S.max(UFS + 3, 0, false) * (1.0/mwt[3]) * NA;
    amrex::Real min_nO2m = 0.0;
    amrex::Real max_nO2m = 0.0;
    if(!streamer_test){
      min_nO4p = S.min(UFS + 6, 0, false) * (1.0/mwt[6]) * NA;
      max_nO4p = S.max(UFS + 6, 0, false) * (1.0/mwt[6]) * NA;
      min_nO2m = S.min(UFS + 9, 0, false) * (1.0/mwt[9]) * NA;
      max_nO2m = S.max(UFS + 9, 0, false) * (1.0/mwt[9]) * NA;
    }
    amrex::Real min_phiV = S.min(UFX, 0, false) * 1.0e-10;
    amrex::Real max_phiV = S.max(UFX, 0, false) * 1.0e-10;
    amrex::Real min_EN = redEfield.min(0, 0, false);
    amrex::Real max_EN = redEfield.max(0, 0, false);
    amrex::Real max_De = coeffs_old.max(dComp_rhoD + E_ID, 0, false);
    amrex::Real min_rho = S.min(0, 0, false);
    amrex::Real max_Edrift_x = spec_drift.max(NUM_E*E_ID + 0, 0, false);
    amrex::Real max_Edrift_y = spec_drift.max(NUM_E*E_ID + 1, 0, false);
    amrex::Real max_Edrift_z = spec_drift.max(NUM_E*E_ID + 2, 0, false);
    amrex::Real max_Edrift = amrex::max(max_Edrift_x, max_Edrift_y, max_Edrift_z);
    amrex::Real Ddtodx2 = (max_De/min_rho) * dt / (dx[0] * dx[0]);
    amrex::Real CFL = max_Edrift * dt / dx[0];
    amrex::Real min_edrift = (max_Edrift == 0.0) ? 1.0:0.3 * dx[0] / max_Edrift;
    amrex::Real min_dielectric = 0.5*dielectric_ts.min(0, 0, false);
#ifdef PELEC_USE_TWO_TEMP
    amrex::Real max_Te = S.max(UFX+6, 0, false); max_Te *= (1.0/11595.0);
#else
    amrex::Real max_Te; ExtrapTe(max_EN, &max_Te); max_Te *= (1.0/11595.0);
#endif
    if(ef_circuit_model == 1) {
      int step_num = parent->levelSteps(0) + ef_circuit_load_num - 1;
      disp_current = (eleVoltage_ts[step_num] - eleVoltage_ts[step_num-1]) / dt * ef_circuit_capacitance;
      flux_curr = (eleVoltage_ts[step_num] == 0) ? 0.0:flux_current / eleVoltage_ts[step_num];
    }

    if (amrex::ParallelDescriptor::IOProcessor()) {
      std::string baseName = "MonitorFile_Level";
      std::string datString = ".dat";
      std::string intString = std::to_string(i);
      std::string monitorFileName = (baseName + intString + datString);

      std::ofstream MonitorFile;
      MonitorFile.open(monitorFileName.c_str(), std::ios::out | std::ios::app);
      MonitorFile << time << "\t" << max_nE << "\t" << max_nO4p << "\t" << max_nO2m << "\t" << max_phiV << "\t" << max_EN  << "\t" << flux_curr <<"\t" << disp_current << "\t" << Ddtodx2  << "\t" << CFL << "\t" << min_dielectric  << "\t" << min_edrift << "\t" << dt << "\t" << max_Tg << "\t" << max_Te <<"\t" << tot_E << "\t" << mcations << "\t" << manions << std::endl;
      MonitorFile.close();
    }
  }
}


void PeleC::writeCircuitFile(amrex::Real time, int step_num){

  // File only needs to be created on one level since data should be the same across all levels
  // Should be called at finest level only

  if (amrex::ParallelDescriptor::IOProcessor()) {
    std::string circuitFileName = "circuit.dat";

    amrex::Real flux_curr = (eleVoltage_ts[step_num] == 0) ? 0.0:flux_current / eleVoltage_ts[step_num];
    std::ofstream CircuitFile;
    CircuitFile.open(circuitFileName.c_str(), std::ios::out | std::ios::app);
    CircuitFile << step_num+1 << "\t" << time  << "\t" << sourceVoltage_ts[step_num]*1.0e-10 << "\t" << eleVoltage_ts[step_num]*1.0e-10 << "\t" << eleVoltage_ts[step_num+1]*1.0e-10  <<  "\t" << sourceCurrent_ts[step_num] << "\t" << eleCurrent_ts[step_num] << "\t" << incidentWave_ts[step_num]*1.0e-10  << "\t" << reflectedWave_ts[step_num]*1.0e-10  << "\t" << flux_curr << "\t" << ef_circuit_capacitance*1.0e19 << std::endl;
    CircuitFile.close();
  }
}

void PeleC::monitorFileSetup(int i){

  if (amrex::ParallelDescriptor::IOProcessor()) {
    std::string baseName = "MonitorFile_Level";
    std::string datString = ".dat";
    std::string intString = std::to_string(i);
    std::string monitorFileName = (baseName + intString + datString);

    std::ofstream MonitorFile;
    MonitorFile.open(monitorFileName.c_str(), std::ios::out);
    if(pac_mechanism){
      MonitorFile << "(1)time[s] \t (2)E/N[Td] \t (3)Te[eV] \t (4)Tgas[k] \t (5)nE[1/cm3] \t (6)nO[1/cm3] \t (7)nOH[1/cm3] \t (8)nH[1/cm3] \t (9)nN2vib[1/cm3] \t (10)nN2ele[1/cm3] \t (11)O2ele[1/cm3] \t (12)O2+[1/cm3] \t (13)N2+[1/cm3] \t (14)O2-[1/cm3] \t (15)O-[1/cm3] \t (16)nCO[1/cm3] \t (17)nCO2[1/cm3] \t (18)nC2H4[1/cm3] \t (19)mO[g] \t (20)mOH[g] \t (21)mH[g] \t (22)mN2vib[g] \t (23)mN2ele[g] \t (24)mO2ele[g] \t (25)mO2+[g] \t (26)mN2+[g] \t (27)mO2-[g] \t (28)mO-[g] \t (29)mCO[g] \t (30)mCO2[g] \t (31)mC2H4[g] \t (32)tot_E[erg] \t (33)dt[s]" << std::endl;
    } else if(airTT_mechanism){
      MonitorFile << "(1)time[s] \t (2)E/N[Td] \t (3)Te[eV] \t (4)Tgas[k] \t (5)nE[1/cm3] \t (6)nO[1/cm3] \t (7)nN2vib[1/cm3] \t (8)nN2ele[1/cm3] \t (9)O2ele[1/cm3] \t (10)O2+[1/cm3] \t (11)N2+[1/cm3] \t (12)O2-[1/cm3] \t (13)O-[1/cm3] \t (14)mO[g] \t (15)mN2vib[g] \t (16)mN2ele[g] \t (17)mO2ele[g] \t (18)mO2+[g] \t (19)mN2+[g] \t (20)mO2-[g] \t (21)mO-[g] \t (22)tot_E[erg] \t (23)dt[s]" << std::endl;
    }else{
      MonitorFile << "(1)time[s] \t (2)max_nE[1/cm3] \t (3)max_nO4+[1/cm3] \t (4)max_nO2-[1/cm3] \t (5)max_phiV[kV] \t (6)max_EN[Td] \t (7)flux_current[C/s] \t (8)disp_current[C/s] \t(9)Ddtodx2 \t (10)CFL \t (11)min_dielectric[s] \t (12)min_drift[s] \t (13)dt[s] \t (14)Tmax[K] \t (15)Temax[eV] \t (16)tot_E[erg] \t (17)mcations[g] \t (18)manions[g]" << std::endl;
    }
    MonitorFile.close();
  }
}

void PeleC::NLConvergenceFileSetup(int i){

  if (amrex::ParallelDescriptor::IOProcessor()) {
    std::string baseName = "NLConvergence_Level";
    std::string datString = ".dat";
    std::string intString = std::to_string(i);
    std::string monitorFileName = (baseName + intString + datString);

    std::ofstream MonitorFile;
    MonitorFile.open(monitorFileName.c_str(), std::ios::out);
    MonitorFile << "(1)step_num \t (2)time[s] \t (3)NL_iter \t (4)NL_ne_l2_resid \t (5)NL_phiV_l2_resid \t (6)lin_iter \t (7)lin_resid" << std::endl;
    MonitorFile.close();
  }
}

void PeleC::circuitFileSetup(){

  if (amrex::ParallelDescriptor::IOProcessor()) {
    std::string circuitFileName = "circuit.dat";
    std::ofstream CircuitFile;
    CircuitFile.open(circuitFileName.c_str(), std::ios::out);
    CircuitFile << "(1)step_num \t (2)time[s] \t (3)sourceVoltage(kV) \t (4)electronVoltage(kV) \t (5)electronVoltage_next(kV) \t (6)sourceCurrent(C/s) \t (7)electronCurrent(C/s) \t (8)incidentWave(kV) \t (9)reflectedWave(kV) \t (10)flux_current(C/s) \t (11)gapCapacitance(pF)" << std::endl;
    CircuitFile.close();
  }
}
#endif
